const replace=(path,text)=>({op:'replaceText',path,from:0,to:0,text});
export const fixtures=[
 {id:'empty',raw:'',edit:{op:'insertText',path:[0],text:'新增正文'}},
 {id:'heading-basic',raw:'## 标题',edit:replace([0,0],'改')},
 {id:'code-fenced',raw:'```js\nconst x = 1;\n```',edit:replace([0,0],'//改\n')},
 {id:'list-empty-item',raw:'*',edit:{op:'insertText',path:[0, 0, 0],text:'新增正文'}},
 {id:'list-tight-start',raw:'3. 第一\n4. 第二',edit:replace([0,0,0,0],'改')},
 {id:'unicode-utf16-edit',raw:'[a😀b](https://example.com)',edit:{op:'replaceText',path:[0,0],from:1,to:3,text:'汉'}},
 {id:'blockquote-empty',raw:'>',edit:{op:'insertText',path:[0, 0],text:'新增正文'}},
 {id:'blockquote-nested-empty',raw:'> >',edit:{op:'insertText',path:[0, 0, 0],text:'新增正文'}},
 {id:'blockquote-empty-surrounded',raw:'前段\n\n>\n\n后段',edit:replace([2,0],'改')},
 {id:'list-nested-loose',raw:'* mock\n\n  3. nested\n  4. second',edit:replace([0,0,1,0,0,0],'改')},
 {id:'marks-adjacent-escaped',raw:'**粗体**_斜体_`code` 与 \\*转义\\* **粗_斜_体**',edit:replace([0,0],'改')},
 {id:'quote-empty',raw:'[quote]\n[/quote]',edit:{op:'setAttrs',path:[0],attrs:{username:'alice'}}},
 {id:'quote-nested',raw:'[quote="alice, post:2, topic:42"]\n外层\n\n[quote]\n内层\n[/quote]\n[/quote]',edit:replace([0,1,0,0],'改')},
 {id:'details-empty',raw:'[details]\n[/details]',edit:{op:'setAttrs',path:[0],attrs:{open:false}}},
 {id:'details-nested',raw:'[details="外层"]\n[details="内层"]\n正文\n[/details]\n[/details]',edit:replace([0,1,1,0],'改')},
 {id:'link-explicit',raw:'[链接](https://example.com/a)',edit:replace([0,0],'改')},
 {id:'link-bare',raw:'https://example.com/a',edit:replace([0,0],'改')},
 {id:'link-angle',raw:'<https://example.com/a>',edit:replace([0,0],'改')},
 {id:'link-title',raw:'[标题](https://example.com/a "说明")',edit:replace([0,0],'改')},
 {id:'link-attachment',raw:'[文件|attachment](upload://abc.pdf)',edit:replace([0,0],'改')},
 {id:'list-loose-bullet',raw:'* 第一段\n\n  第二段\n\n* 另项',edit:replace([0,0,1,0],'改')},
 {id:'list-loose-ordered',raw:'3. 第一项\n\n4. 第二项',edit:replace([0,1,0,0],'改')},
 {id:'html-small-nested',raw:'前<small>小<small>更小</small></small>后',edit:replace([0,1,1,0],'改')},
 {id:'html-ruby-attrs',raw:'<ruby lang="ja">漢<rt lang="ja">かん</rt></ruby>',edit:{op:'setAttrs',path:[0,0],attrs:{htmlAttrs:{lang:'zh'}}}},
 {id:'html-empty-kbd',raw:'前<kbd></kbd>后',edit:{op:'setAttrs',path:[0,1],attrs:{tag:'small'}}},
 {id:'html-block',raw:'<div>\n<strong>原始 HTML</strong>\n</div>',edit:replace([0,0],'<!--编辑-->')},
 {id:'footnote-named-multi-ref',raw:'甲[^name]乙[^name]\n\n[^name]: 命名脚注',edit:replace([0,1,0,0],'改')},
 {id:'footnote-block',raw:'引用[^long]\n\n[^long]: 第一段\n\n    第二段',edit:replace([0,1,1,0],'改')},
 // 属性不作强类型收窄：覆盖官方 JSON attrs 的隐式转换。
 {"id": "attrs-review-0", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": null}}},
 {"id": "attrs-review-1", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": false}}},
 {"id": "attrs-review-2", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": 0}}},
 {"id": "attrs-review-3", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": "2"}}},
 {"id": "attrs-review-4", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": 2}}},
 {"id": "attrs-review-5", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": {}}}},
 {"id": "attrs-review-6", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": []}}},
 {"id": "attrs-review-7", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": null}}},
 {"id": "attrs-review-8", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": false}}},
 {"id": "attrs-review-9", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": 0}}},
 {"id": "attrs-review-10", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": "2"}}},
 {"id": "attrs-review-11", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": 2}}},
 {"id": "attrs-review-12", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": {}}}},
 {"id": "attrs-review-13", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"order": []}}},
 {"id": "attrs-review-14", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": null}}},
 {"id": "attrs-review-15", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": false}}},
 {"id": "attrs-review-16", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": 0}}},
 {"id": "attrs-review-17", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": "2"}}},
 {"id": "attrs-review-18", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": 2}}},
 {"id": "attrs-review-19", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": {}}}},
 {"id": "attrs-review-20", "raw": "3. a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": []}}},
 {"id": "attrs-review-21", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": null}}},
 {"id": "attrs-review-22", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": false}}},
 {"id": "attrs-review-23", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": 0}}},
 {"id": "attrs-review-24", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": "2"}}},
 {"id": "attrs-review-25", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": 2}}},
 {"id": "attrs-review-26", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": {}}}},
 {"id": "attrs-review-27", "raw": "* a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": []}}},
 {"id": "attrs-review-28", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": null}}},
 {"id": "attrs-review-29", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": false}}},
 {"id": "attrs-review-30", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": 0}}},
 {"id": "attrs-review-31", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": "2"}}},
 {"id": "attrs-review-32", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": 2}}},
 {"id": "attrs-review-33", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": {}}}},
 {"id": "attrs-review-34", "raw": "```\na\n```", "edit": {"op": "setAttrs", "path": [0], "attrs": {"params": []}}},
 {"id": "attrs-review-35", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": null}}},
 {"id": "attrs-review-36", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": false}}},
 {"id": "attrs-review-37", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": 0}}},
 {"id": "attrs-review-38", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": "2"}}},
 {"id": "attrs-review-39", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": 2}}},
 {"id": "attrs-review-40", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": {}}}},
 {"id": "attrs-review-41", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"tag": []}}},
 {"id": "attrs-review-42", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": null}}},
 {"id": "attrs-review-43", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": false}}},
 {"id": "attrs-review-44", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": 0}}},
 {"id": "attrs-review-45", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": "2"}}},
 {"id": "attrs-review-46", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": 2}}},
 {"id": "attrs-review-47", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": {}}}},
 {"id": "attrs-review-48", "raw": "a<small>b</small>", "edit": {"op": "setAttrs", "path": [0, 1], "attrs": {"htmlAttrs": []}}},
 {"id": "attrs-review-49", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": null}}},
 {"id": "attrs-review-50", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": false}}},
 {"id": "attrs-review-51", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": 0}}},
 {"id": "attrs-review-52", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": "2"}}},
 {"id": "attrs-review-53", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": 2}}},
 {"id": "attrs-review-54", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": {}}}},
 {"id": "attrs-review-55", "raw": "[quote]\na\n[/quote]", "edit": {"op": "setAttrs", "path": [0], "attrs": {"username": []}}},
 {"id": "attrs-heading-fraction", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": 2.5}}},
 {"id": "attrs-heading-negative", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": -2}}},
 {"id": "attrs-heading-hex", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": "0x2"}}},
 {"id": "attrs-heading-binary", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": "0b10"}}},
 {"id": "attrs-heading-nan", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": "no"}}},
 {"id": "attrs-heading-array", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": [2]}}},
 {"id": "attrs-heading-whitespace", "raw": "# a", "edit": {"op": "setAttrs", "path": [0], "attrs": {"level": " 2 "}}},
 {"id": "attrs-tight-multi-zero", "raw": "* a\n* b", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": 0}}},
 {"id": "attrs-tight-multi-array", "raw": "* a\n* b", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": []}}},
 {"id": "attrs-tight-multi-object", "raw": "* a\n* b", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": {}}}},
 {"id": "attrs-tight-multi-empty", "raw": "* a\n* b", "edit": {"op": "setAttrs", "path": [0], "attrs": {"tight": ""}}},
];
